vFiles = c ("average_costs.csv",
"averageThreshold.csv",
"average_time_to_be_delivered.csv",
"average_time_to_deliver.csv",
"competition_between_LH_Antwerp.csv",
"nb_stocks_awaiting.csv",
"number_empty_stock_final_dest.csv",
"number_empty_stock_warehouses.csv",
"share_leaving_quantities_per_transport_mode_Antwerpen.csv",
"share_leaving_quantities_per_transport_mode_Basse-Normandie.csv",
"share_leaving_quantities_per_transport_mode_Centre.csv",
"share_leaving_quantities_per_transport_mode_Haute-Normandie.csv",
"share_leaving_quantities_per_transport_mode_Ile-de-France.csv",
"share_leaving_quantities_per_transport_mode_Le Havre.csv",
"share_leaving_quantities_per_transport_mode_Picardie.csv",
"share_leaving_vehicles_per_transport_mode_Antwerpen.csv",
"share_leaving_vehicles_per_transport_mode_Basse-Normandie.csv",
"share_leaving_vehicles_per_transport_mode_Centre.csv",
"share_leaving_vehicles_per_transport_mode_Haute-Normandie.csv",
"share_leaving_vehicles_per_transport_mode_Ile-de-France.csv",
"share_leaving_vehicles_per_transport_mode_Le Havre.csv",
"share_leaving_vehicles_per_transport_mode_Picardie.csv",
"share_port_origin_region_Antwerpen.csv",
"share_port_origin_region_Basse-Normandie.csv",
"share_port_origin_region_Centre.csv",
"share_port_origin_region_Haute-Normandie.csv",
"share_port_origin_region_Ile-de-France.csv",
"share_port_origin_region_Le Havre.csv",
"share_port_origin_region_Picardie.csv",
"share_transport_mode_Antwerpen.csv",
"share_transport_mode_Basse-Normandie.csv",
"share_transport_mode_Centre.csv",
"share_transport_mode.csv",
"share_transport_mode_Haute-Normandie.csv",
"share_transport_mode_Ile-de-France.csv",
"share_transport_mode_Le Havre.csv",
"share_transport_mode_Picardie.csv",
"share_transport_mode_quantities_Antwerpen.csv",
"share_transport_mode_quantities_Basse-Normandie.csv",
"share_transport_mode_quantities_Centre.csv",
"share_transport_mode_quantities.csv",
"share_transport_mode_quantities_Haute-Normandie.csv",
"share_transport_mode_quantities_Ile-de-France.csv",
"share_transport_mode_quantities_Le Havre.csv",
"share_transport_mode_quantities_Picardie.csv",
"stocks_final_dests.csv",
"stocks_warehouses.csv",
"strat1_threshold_adoption_share.csv",
"strat2_threshold_adoption_share.csv",
"strat3_threshold_adoption_share.csv",
"strat4_threshold_adoption_share.csv",
"strategies_adoption_share.csv",
"traffic_evolution_CSN.csv",
"vehicles_occupancy_maritime.csv",
"vehicles_occupancy_river.csv",
"vehicles_occupancy_road.csv",
"vehicles_occupancy_secondary.csv")

allData = data.frame(step = 0:15999);
for (filename in vFiles) {
	print(filename);
	df = read.csv(filename, sep=";");
	allData = merge(allData, df)
}